//! Windowing-agnostic input and response types.
//!
//! [`Scene::handle`](crate::Scene::handle) consumes an [`Input`] and returns a
//! [`Response`]. Neither type names a windowing library, so a host that already
//! owns its event loop — a browser page driving a `<canvas>`, say — can feed the
//! scene directly without adopting winit's application model.
//!
//! With the `winit` feature enabled,
//! [`WinitInput::map`](crate::winit_adapter::WinitInput::map) maps a
//! `winit::event::WindowEvent` onto this vocabulary, and
//! [`SceneRunner`](crate::SceneRunner) is a thin shell on top.
//!
//! # Coordinates
//! All positions are **physical pixels** relative to the surface's top-left
//! corner, matching [`Engine`](crate::Engine)'s surface size and every
//! [`Drawable`](crate::Drawable) coordinate. A host working in logical units
//! (CSS pixels, for instance) multiplies by its own scale factor before
//! building an [`Input`].

// ---------------------------------------------------------------------------
// Pointers
// ---------------------------------------------------------------------------

/// Which pointer an [`Input::Pointer`] came from.
///
/// Mouse and touch are deliberately distinct rather than unified behind a
/// single numeric id: a scene tracks one mouse cursor (which drives rubber-band
/// selection) but any number of simultaneous fingers, each dragging
/// independently. Collapsing them here would hide a difference the scene
/// genuinely acts on.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum PointerId {
    /// The mouse cursor.
    Mouse,
    /// A touch point, identified by the platform's finger id.
    Touch(u64),
}

/// What a pointer just did.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum PointerPhase {
    /// Pressed down (left mouse button, or a finger landing).
    Down,
    /// Moved while the pointer is still present.
    Move,
    /// Released normally.
    Up,
    /// Ended abnormally — the finger was cancelled by the system, or the cursor
    /// left the surface mid-drag.
    ///
    /// A scene treats this as a release at the current position rather than
    /// reverting: by the time it arrives the drawables have already moved on
    /// screen, so reverting would surprise the user and leave the host's
    /// persisted state disagreeing with what is displayed.
    Cancel,
}

// ---------------------------------------------------------------------------
// Keyboard
// ---------------------------------------------------------------------------

/// The keys a [`Scene`](crate::Scene) acts on.
///
/// Deliberately small and haboard's own, rather than a re-export of a
/// windowing library's key type: re-exporting would put that library back into
/// an embedder's dependency graph through the front door. Keys the scene does
/// not act on map to [`Key::Unidentified`].
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Key {
    Escape,
    Delete,
    Backspace,
    ArrowLeft,
    ArrowRight,
    ArrowUp,
    ArrowDown,
    /// A printable character, already lower-cased for letters so that shortcut
    /// matching does not depend on shift state.
    Character(char),
    /// Any key the scene has no behaviour for.
    Unidentified,
}

/// Keyboard modifier state.
///
/// Held by the scene and updated via [`Input::Modifiers`]; a host that never
/// sends one simply gets the unmodified behaviour throughout.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default)]
pub struct Modifiers {
    pub ctrl: bool,
    pub shift: bool,
    pub alt: bool,
    /// Command on macOS, Windows/Super elsewhere.
    pub meta: bool,
}

impl Modifiers {
    /// No modifiers held.
    pub const NONE: Self = Self {
        ctrl: false,
        shift: false,
        alt: false,
        meta: false,
    };
}

// ---------------------------------------------------------------------------
// Input
// ---------------------------------------------------------------------------

/// A single input event delivered to [`Scene::handle`](crate::Scene::handle).
#[derive(Debug, Clone, Copy, PartialEq)]
#[non_exhaustive]
pub enum Input {
    /// A pointer was pressed, moved, released or cancelled. `x`/`y` are
    /// physical pixels from the surface's top-left corner.
    Pointer {
        id: PointerId,
        phase: PointerPhase,
        x: f32,
        y: f32,
    },
    /// A key changed state. `repeat` marks an auto-repeat generated by holding
    /// the key, which some actions (delete, paste) deliberately ignore.
    Key {
        key: Key,
        pressed: bool,
        repeat: bool,
    },
    /// The modifier state changed.
    Modifiers(Modifiers),
    /// The surface was resized, in physical pixels.
    Resize { width: u32, height: u32 },
}

// ---------------------------------------------------------------------------
// Response
// ---------------------------------------------------------------------------

/// Whether an [`Input`] finished a change worth persisting.
///
/// Holding an arrow key nudges the selection on every auto-repeat. Each of
/// those really did change the scene, so reporting nothing would be a lie — but
/// reporting a finished change tens of times a second asks every host to
/// rediscover debouncing. [`Defer`](Commit::Defer) is the honest third answer:
/// something changed, and more of the same is still coming.
///
/// A host with cheap persistence can treat `Defer` and `Now` alike. A host with
/// expensive persistence defers on `Defer` and flushes on `Now`.
///
/// # Deferred commits are owed, not dropped
/// A deferred run is normally flushed by the key release that ends it. If the
/// host tears the scene down first — a closing window, a route change — the
/// release never arrives, so ask
/// [`Scene::take_pending_commit`](crate::Scene::take_pending_commit) on the way
/// out and save if it says one is outstanding.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default)]
pub enum Commit {
    /// Nothing finished; there is nothing to persist.
    #[default]
    No,
    /// Something changed, but it is part of a run that has not ended yet.
    Defer,
    /// A change finished. Persist now.
    Now,
}

impl Commit {
    /// Whether anything changed at all — true for both [`Defer`](Commit::Defer)
    /// and [`Now`](Commit::Now).
    pub fn is_change(self) -> bool {
        !matches!(self, Self::No)
    }

    /// Whether the host should persist immediately.
    pub fn is_now(self) -> bool {
        matches!(self, Self::Now)
    }
}

/// What handling an [`Input`] did.
///
/// `#[non_exhaustive]`: construct one with [`Response::default`] and read the
/// fields, so that later additions are not a breaking change.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default)]
#[non_exhaustive]
pub struct Response {
    /// The scene acted on this input. A host can use this to decide whether to
    /// let the event propagate — on the web, whether to call
    /// `preventDefault()`.
    pub handled: bool,
    /// The scene's appearance changed, so the next frame will differ.
    ///
    /// **Advisory.** It is set conservatively by anything that mutates scene
    /// state through [`Scene::handle`](crate::Scene::handle), but a host that
    /// mutates drawables directly through
    /// [`Scene::drawables`](crate::Scene::drawables) bypasses it — call
    /// [`Scene::request_redraw`](crate::Scene::request_redraw) in that case.
    /// Rendering unconditionally every frame is always correct.
    pub redraw_needed: bool,
    /// Whether an interaction finished in a state worth persisting — a drag
    /// released, an edit keystroke applied, an undo performed.
    ///
    /// Computed from what actually changed rather than from the shape of the
    /// input, so a keystroke the scene ignored reports [`Commit::No`] even
    /// though a key was undeniably pressed.
    pub commit: Commit,
    /// The set of selected drawables changed.
    pub selection_changed: bool,
}

impl Response {
    /// A response reporting that nothing happened.
    pub const IGNORED: Self = Self {
        handled: false,
        redraw_needed: false,
        commit: Commit::No,
        selection_changed: false,
    };

    /// A response reporting that the scene acted on the input and needs to be
    /// redrawn, with nothing committed and no selection change.
    pub(crate) const HANDLED: Self = Self {
        handled: true,
        redraw_needed: true,
        commit: Commit::No,
        selection_changed: false,
    };
}
